server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    url: jdbc:mysql://localhost:3306/hireconnect_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

jwt:
  refresh-expiration: 604800000

auth:
  reset-otp-expiration-minutes: 10
  oauth-success-redirect-url: http://localhost:4200/oauth-success
  oauth-failure-redirect-url: http://localhost:4200/login

logging:
  file:
    path: ../logs/auth-service
